# ======================
# Общие настройки игры
# ======================

[game]
initial_resources = 10000
max_level = 20
match_power_threshold = 100

# ======================
# Ремонт корабля
# ======================

[repair]
cost_per_power = 0.05             # C — цена починки единицы мощности
time_per_1000_power_sec = 60      # T — секунд на 1000 мощи
min_cost = 1                      # минимальная цена ремонта в ресурсах


# ======================
# Улучшение модулей
# ======================

[upgrade]
cost_exponent = 1.5               # степень роста стоимости
cost_multiplier = 100             # базовый множитель стоимости


# ======================
# Расчёт мощи
# ======================

[power]
maneuver_multiplier = 1.0         # множитель для манёвренности (1 + M)
base_multiplier = 10.0            # базовый множитель мощности корпуса
armor_cap = 99.9                  # максимальная защита (армора), чтобы избежать деления на 0
speed_divisor = 100.0             # делитель скорости для пушки (S / X)


# ======================
# Параметры админки
# ======================
[admins]
bot_name = "space_lords_dev_bot"
admins_array = [
    269251765,
    462775464,
    5128641039,
    6593984699
]

# ======================
# Арена (награды)
# ======================
[arena_rewards]
win_multiplier = 0.01
loss_multiplier = 0.003
spread_exponent = 1.5
