# ======================
# Общие настройки игры
# ======================

[game]
initial_resources = 100000
max_level = 20
match_power_threshold = 100
damage_deviation = 20
guns_count = 8
hulls_count = 6

# ======================
# Ремонт корабля
# ======================

[repair]
cost_per_power = 0.05             # C — цена починки единицы мощности
time_per_1000_power_sec = 1      # T — секунд на 1000 мощи
min_cost = 1                      # минимальная цена ремонта в ресурсах


# ======================
# Улучшение модулей
# ======================

[upgrade]
cost_exponent = 1.5               # степень роста стоимости
cost_multiplier = 100             # базовый множитель стоимости


# ======================
# Расчёт мощи
# ======================

[power]
maneuver_multiplier = 1.0         # множитель для манёвренности (1 + M)
base_multiplier = 10.0            # базовый множитель мощности корпуса
armor_cap = 99.9                  # максимальная защита (армора), чтобы избежать деления на 0
speed_divisor = 100.0             # делитель скорости для пушки (S / X)


# ======================
# Параметры админки
# ======================
[admins]
bot_name = 'space_lords_bot'
admins_array = [
    269251765,
    462775464,
    5128641039,
    6593984699
]

# ======================
# Арена (награды)
# ======================
[arena_rewards]
win_multiplier = 0.01
loss_multiplier = 0.003
spread_exponent = 1.5

# ======================
# Названия (идентификаторы) экранов
# ======================
[screens]
ADMIN = 'ADMIN'
ADMIN_UTM_ALL = 'ADMIN_UTM_ALL'
ADMIN_CREATE_UTM = 'ADMIN_CREATE_UTM'
ADMIN_REGISTRATION_INFO = 'ADMIN_REGISTRSTION_INFO'
ADMIN_PLAYER_TABLES = 'ADMIN_PLAYER_TABLES'
ADMIN_SET_RESOURCES = 'ADMIN_SET_RESOURCES'
ADMIN_BROADCAST = 'ADMIN_BROADCAST'

ARENA = 'АРЕНА'
ARENA_QUEUE = 'ARENA_QUEUE'

DEFAULT = 'ГЛАВНОЕ МЕНЮ'

MAP = 'КАРТА'
PLANET_1 = 'PLANET_1'
PLANET_2 = 'PLANET_2'
PLANET_3 = 'PLANET_3'
PLANET_4 = 'PLANET_4'
POST_PLANET_1 = 'POST_PLANET_1'
POST_PLANET_2 = 'POST_PLANET_2'
POST_PLANET_3 = 'POST_PLANET_3'
POST_PLANET_4 = 'POST_PLANET_4'
SECTORS = 'SECTORS'
SECTOR_1 = 'SECTOR_1'
SECTOR_2 = 'SECTOR_2'
SECTOR_3 = 'SECTOR_3'
SECTOR_4 = 'SECTOR_4'
POST_SECTOR_1 = 'POST_SECTOR_1'
POST_SECTOR_2 = 'POST_SECTOR_2'
POST_SECTOR_3 = 'POST_SECTOR_3'
POST_SECTOR_4 = 'POST_SECTOR_4'

PLANET = 'PLANET'
POST_PLANET_CLAIM = 'POST_PLANET_CLAIM'
POST_PLANET_GATHER = 'POST_PLANET_GATHER'
PLANET_UPGRADE = 'PLANET_UPGRADE'
POST_PLANET_UPGRADE = 'POST_PLANET_UPGRADE'
PLANET_ENEMY = 'PLANET_ENEMY'
PLANET_FIGHT = 'PLANET_FIGHT'

# Определяем идентификаторы экранов
# Главные экраны
SHIP = 'КОРАБЛЬ'
SHIP_WEAPON = 'SHIP_WEAPON'
SHIP_BODY = 'SHIP_BODY'
# Улучшения
SHIP_WEAPON_UPGRADE = 'SHIP_WEAPON_UPGRADE'
POST_SHIP_WEAPON_UPGRADE = 'POST_SHIP_WEAPON_UPGRADE'
SHIP_HULL_UPGRADE = 'SHIP_HULL_UPGRADE'
POST_HULL_UPGRADE = 'POST_HULL_UPGRADE'
# Замены
SHIP_WEAPON_CHANGE = 'SHIP_WEAPON_CHANGE'
POST_SHIP_WEAPON = 'POST_SHIP_WEAPON'  # динамический handler
SHIP_HULL_CHANGE = 'SHIP_HULL_CHANGE'
POST_SHIP_BODY = 'POST_SHIP_BODY'      # динамический handler
# Ремонт
SHIP_BODY_REPAIR = 'SHIP_BODY_REPAIR'
POST_SHIP_BODY_REPAIR = 'POST_SHIP_BODY_REPAIR'