name: CI/CD (Auto PROD/DEV)

permissions:
  contents: read
  actions: write

on:
  workflow_dispatch:  # Добавляем ручной триггер
  push:
    branches:
      - main
      - dev
      - hotfix

jobs:
  lint:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.10"

      - name: Install dependencies
        run: |
          pip install flake8 black

      - name: Run Black (check formatting)
        run: black .

      - name: Run flake8
        run: flake8 . --count --show-source --statistics

  build-and-push:
    needs: lint
    runs-on: ubuntu-latest

    steps:
      - name: Check out repository
        uses: actions/checkout@v2

      - name: Determine environment suffix
        id: vars
        run: |
          if [[ "${GITHUB_REF}" == "refs/heads/main" ]]; then
            echo "env_suffix=PROD" >> $GITHUB_OUTPUT
          else
            echo "env_suffix=DEV" >> $GITHUB_OUTPUT
          fi

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1

      - name: Log in to Docker Hub
        uses: docker/login-action@f4ef78c080cd8ba55a85445d5b36e214a81df20a
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Build and push Docker image
        uses: docker/build-push-action@3b5e8027fcad23fda98b2e3ac259d8d67585f671

        with:
          context: .
          file: Dockerfile
          platforms: linux/arm64,linux/amd64
          build-args: |
            BOT_TOKEN=${{ secrets[format('BOT_TOKEN_{0}', steps.vars.outputs.env_suffix)] }}
            DB_USERNAME=${{ secrets[format('DB_USERNAME_{0}', steps.vars.outputs.env_suffix)] }}
            DB_PASSWORD=${{ secrets[format('DB_PASSWORD_{0}', steps.vars.outputs.env_suffix)] }}
            DB_IP=${{ secrets[format('DB_IP_{0}', steps.vars.outputs.env_suffix)] }}
            DB_PORT=${{ secrets[format('DB_PORT_{0}', steps.vars.outputs.env_suffix)] }}
            DB_NAME=${{ secrets[format('DB_NAME_{0}', steps.vars.outputs.env_suffix)] }}
          push: true
          tags: ${{ secrets[format('DOCKER_REGISTRY_{0}', steps.vars.outputs.env_suffix)] }}/${{ secrets[format('DOCKER_IMAGE_{0}', steps.vars.outputs.env_suffix)] }}:${{ github.sha }},${{ secrets[format('DOCKER_REGISTRY_{0}', steps.vars.outputs.env_suffix)] }}/${{ secrets[format('DOCKER_IMAGE_{0}', steps.vars.outputs.env_suffix)] }}:latest

  deploy:
    needs: build-and-push
    runs-on: ubuntu-latest

    steps:
      - name: Determine environment suffix
        id: vars
        run: |
          if [[ "${GITHUB_REF}" == "refs/heads/main" ]]; then
            echo "env_suffix_lower=prod" >> $GITHUB_OUTPUT
          else
            echo "env_suffix_lower=test" >> $GITHUB_OUTPUT
          fi

      - name: SSH Deploy
        uses: appleboy/ssh-action@v1.2.1
        with:
          host: ${{ secrets.SSH_HOST }}
          username: ${{ secrets.SSH_USERNAME }}
          password: ${{ secrets.SSH_KEY }}
          port: ${{ secrets.SSH_PORT }}
          script: |
            cd app
            docker-compose stop backend-${{ steps.vars.outputs.env_suffix_lower }}
            docker system prune -f
            docker-compose pull backend-${{ steps.vars.outputs.env_suffix_lower }}
            docker-compose up -d backend-${{ steps.vars.outputs.env_suffix_lower }}
            sleep 5
            docker-compose ps backend-${{ steps.vars.outputs.env_suffix_lower }}
            docker-compose logs -t --tail="50" backend-${{ steps.vars.outputs.env_suffix_lower }}
